spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion_de_tache
    username: root
    password:
  jpa:
  
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.mysql5dialect
    generate-ddl: true
    show-sql: false
    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: <ahmed.tiba.developpeur@gmail.com">
    password: <xplruvlghwyyuyey>
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
